//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// 此原始程式碼由 xsd 版本=4.6.1055.0 自動產生。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/huehue.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/huehue.xsd", IsNullable=false)]
public enum car {
    
    /// <remarks/>
    Audi,
    
    /// <remarks/>
    Golf,
    
    /// <remarks/>
    BMW,
}
